name: MineSweeper
version: '${version}'
main: de.joshua.MineSweeper
api-version: '1.20'

commands:
  MineSweeper:
    description: MineSweeper Commands
    usage: minesweeper <start|reconnect> <width> <height> <mines>
    aliases:
      - ms